/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package helloworld1;


import helloworld1.lesson1.*;
import helloworld1.lesson2.*;
import helloworld1.lesson3.*;

public class App {

    public static void main(String[] args) {
		
		// Lesson3.fixBandsImperatively();
		Lesson3.fixBands();
		// Lesson2 appendix
		// L2a.controllerL2a();
		// Lesson2
		// Lesson2.runRace();
		// Lesson2.runRaceFunc();
		// Lesson2.zeroOne();

		// Lesson1
		// Lesson1.nameLength();
		// Lesson1.square();
		// hashNamesFunc();
		// reduceSum();
		// countSam();
		// Lesson1.execise2();

	}

}
