/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package helloworld1;


import helloworld1.example.Example;
import helloworld1.lesson1.*;
import helloworld1.lesson2.*;
import helloworld1.lesson3.*;

public class App {

    public static void main(String[] args) {
		
		// Example
		Example.run();

		// Lesson3
		// Lesson3.fixBandsImperatively();
		// Lesson3.fixBands();

		// Lesson3 appendix
		// Lesson3A.run();


		// Lesson2
		// Lesson2.runRace();
		// Lesson2.runRaceFunc();
		// Lesson2.zeroOne();

		// Lesson1
		// Lesson1.nameLength();
		// Lesson1.nameLengthFunc();
		// Lesson1.square();
		// hashNamesFunc();
		// Lesson1.reduceSum();
		// countSam();
		// Lesson1.execise2();
		// Lesson1.square();
		// Lesson1.squareFunc();
		// Lesson1.useOriginalFunc();
	}

}
